[package]
name = "rpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.6"
tempfile = "3.2.0"
bytes = "1.1.0"
tokio = { version = "1", features = ["full"] }
rusqlite = "0.26.1"
sha2 = "0.9.8"
hex = "0.4.3"
ar = "0.9.0"
tar = "0.4.37"
xz = "0.1.0"
itertools = "0.10.1"

[dependencies.clap]
version = "2.33.3"
default-features = true